### ISSUE TITLE
Create quests

### ISSUE THREAD

**Issue by yegorf1** [UntitledRPGTeam/Untitled-RPG-game#2]
Create quests.
Quests will have:
- Name
- Description
- Owner
- Some runnabel/lua script that checks that quest is completed
- Reward

**Comment by joakim1999** [comment]
What do you need help with?

**Comment by yegorf1** [comment]
@joakim1999 Don't know how to implement checking, that quest is completed Maybe we should define all quest types and use enums

**Comment by joakim1999** [comment]
@yegorf1  What about notify system?

**Comment by yegorf1** [comment]
?
